"""add device and maintenance log tables

Revision ID: 07b4fe21d9e5
Revises: 13c2731be2f3
Create Date: 2025-05-30 00:18:17.069414

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '07b4fe21d9e5'
down_revision = '13c2731be2f3'
branch_labels = None
depends_on = None

def upgrade():
    # Create devices table first
    op.create_table('devices',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('serial_number', sa.String(), nullable=False),
        sa.Column('model', sa.String(), nullable=True),
        sa.Column('manufacturer', sa.String(), nullable=True),
        sa.Column('purchase_date', sa.Date(), nullable=True),
        sa.Column('location', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('serial_number')
    )
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    # Now create tables that reference devices
    op.create_table('device_maintenance_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('device_id', sa.Integer(), nullable=False),
        sa.Column('maintenance_date', sa.DateTime(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('performed_by', sa.String(), nullable=True),
        sa.Column('remarks', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['device_id'], ['devices.id'])
    )
    op.create_index(op.f('ix_device_maintenance_logs_id'), 'device_maintenance_logs', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_device_maintenance_logs_id'), table_name='device_maintenance_logs')
    op.drop_table('device_maintenance_logs')
    # ### end Alembic commands ###
