"""add date column to invoices

Revision ID: 13c2731be2f3
Revises: c331c0ee4c80
Create Date: 2025-05-29 23:27:40.569070

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '13c2731be2f3'
down_revision = 'c331c0ee4c80'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('invoice_number', sa.String(), nullable=False))
    op.add_column('invoices', sa.Column('date', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'invoices', ['invoice_number'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='unique')
    op.drop_column('invoices', 'date')
    op.drop_column('invoices', 'invoice_number')
    # ### end Alembic commands ###
