"""add staff address hourly_rate role department appointment_type

Revision ID: 7973626daea5
Revises: 07b4fe21d9e5
Create Date: 2025-06-07 08:09:44.335000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7973626daea5'
down_revision = '07b4fe21d9e5'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('address', sa.String(), nullable=True))
    op.add_column('staff', sa.Column('hourly_rate', sa.Float(), nullable=True))
    op.add_column('staff', sa.Column('role', sa.String(), nullable=True))
    op.add_column('staff', sa.Column('department', sa.String(), nullable=True))
    op.add_column('staff', sa.Column('appointment_type', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'appointment_type')
    op.drop_column('staff', 'department')
    op.drop_column('staff', 'role')
    op.drop_column('staff', 'hourly_rate')
    op.drop_column('staff', 'address')
    # ### end Alembic commands ###
