"""Add fingerprint templates and update attendance

Revision ID: add_fingerprint_integration
Revises: 
Create Date: 2025-08-07 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_fingerprint_integration'
down_revision = None  # Update this to the latest revision ID
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create fingerprint_templates table
    op.create_table('fingerprint_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('template_data', sa.Text(), nullable=False),
    sa.Column('finger_position', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=False),
    sa.Column('enrollment_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id')
    )
    op.create_index(op.f('ix_fingerprint_templates_id'), 'fingerprint_templates', ['id'], unique=False)
    
    # Add new columns to attendance_records table
    op.add_column('attendance_records', sa.Column('fingerprint_verified', sa.Boolean(), nullable=True))
    op.add_column('attendance_records', sa.Column('verification_confidence', sa.Integer(), nullable=True))
    op.add_column('attendance_records', sa.Column('auth_method', sa.String(), nullable=True))
    op.add_column('attendance_records', sa.Column('device_info', sa.Text(), nullable=True))
    op.add_column('attendance_records', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('attendance_records', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    
    # Set default values for existing records
    op.execute("UPDATE attendance_records SET fingerprint_verified = false WHERE fingerprint_verified IS NULL")
    op.execute("UPDATE attendance_records SET auth_method = 'manual' WHERE auth_method IS NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove columns from attendance_records table
    op.drop_column('attendance_records', 'updated_at')
    op.drop_column('attendance_records', 'created_at')
    op.drop_column('attendance_records', 'device_info')
    op.drop_column('attendance_records', 'auth_method')
    op.drop_column('attendance_records', 'verification_confidence')
    op.drop_column('attendance_records', 'fingerprint_verified')
    
    # Drop fingerprint_templates table
    op.drop_index(op.f('ix_fingerprint_templates_id'), table_name='fingerprint_templates')
    op.drop_table('fingerprint_templates')
    
    # ### end Alembic commands ###
