"""add user warehouse and section access tables

Revision ID: d7f26d3030fd
Revises: 44156d030244
Create Date: 2025-06-09 22:09:47.937656

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd7f26d3030fd'
down_revision = '44156d030244'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_section_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'section_name', name='_user_section_uc')
    )
    op.create_index(op.f('ix_user_section_access_id'), 'user_section_access', ['id'], unique=False)
    op.create_table('user_warehouse_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'warehouse_id', name='_user_warehouse_uc')
    )
    op.create_index(op.f('ix_user_warehouse_access_id'), 'user_warehouse_access', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_warehouse_access_id'), table_name='user_warehouse_access')
    op.drop_table('user_warehouse_access')
    op.drop_index(op.f('ix_user_section_access_id'), table_name='user_section_access')
    op.drop_table('user_section_access')
    # ### end Alembic commands ###
